### ISSUE TITLE
Discussing about merging types from janaagaard75

### ISSUE THREAD

**Issue by KonstantinKai** [KonstantinKai/DefinitelyTyped#1]
@janaagaard75, lets discuss in this issue about merging your changes :)

**Comment by KonstantinKai** [comment]
@janaagaard75 about your mail 
```
Sorry for all the mess I created in the jaagaard75 branch. I guess you already have imported everything from my type definition file.

What is missing in order to get the jaagaard75 branch merged to master? At lot of tests?
```

Need to rollback your changes to Audio & AV namespace which you did do to my (please cancel commit https://github.com/KonstantinKai/DefinitelyTyped/commit/a36d4ccc2ea02cb8fd336db43fe5d879368d9d53), remove vector icons from source, change all `export namespace` to `declare ...`, then I will check all tests and code style, and after all these things I will create PR to the main repo.

**Comment by janaagaard75** [comment]
Reverted the AV changes and vector-icons, and changed all `export namespace` to `declare namespace`.

Should we remove all the `export` keywords? I think they are unnecessary.

**Comment by KonstantinKai** [comment]
@janaagaard75, I've made final corrections, and I'm ready to make PR. Please, look at the source and give me your final opinion.

**Comment by janaagaard75** [comment]
I don't have any more comments now. My votes goes for taking a lot of small steps instead of single big one. That being said, I don't know how much trouble it is to make a pull request.
